sudo: false

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers

jdk: oraclejdk8

language: scala

scala:
  - 2.11.7

script:
  - "sbt scalastyle"
  - "sbt coffeelint"
  - "sbt test"
  - "sbt scrapePlay"
  - "sbt scrapeUpload"

env:
  global:
  - secure: SNxviA06HhGdc/+tJxBlYgrjCyWHOdScf8Nw/okMV7/O0zwYtoaq9VUWs2h+unUsVhDOUNTg7J3DwgWXCJMzAZu7tHKBTbg8+h0AdSDN4eYCv+v2JW5l5YVa9yDKcmsNPRIx0+dLzUEflfgfQv6psdai0pFSt/mGg0t0jYEk3ms=
  - secure: lbuteqpmcEG+ZpGODuHp3qj4+ScWZxMpkjIizDf5cQIRsLY2pW26JAHaxHvanFDFOdzbxORaYIrIDy/XlT28Ct2SUeAr2Lc7JXFaTs9vwYoR+6xNuqn1zJDa9Utfk3WmKQ9WCMJKQFMPMWvEPpqAhEFKwkZO/SaeD15oHcnr1Fg=
