sudo: false

# cache stuff, hopefully shortening build times
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers

jdk: oraclejdk8
language: scala
scala:
  - 2.11.7
script:
  - "sbt scalastyle"
  - "sbt coffeelint"
  - "sbt test"
after_success:
  - sbt scrapePlay
  - sbt scrapeUpload
env:
  global:
  - secure: YOyMd40Hk0Cm6JkgP8ABQw3NfN6T/TG8Kl3GOINBEdfgVlAvXDxelwbAmssYYr2Er78Qi6fn22VmcOmjW04fPJCIXknPJLFTSFP+SSmYhHKbyehvLfuNu2dNk3vh3YNfHFFdhYXpQW16P0byVJfrLuXhYItlzcGvNhtLlDJivvQ=
  - secure: HDQvD4RqBSrDZIMIJgZ5atjFyZiwSDBFwWq1G9JAMfWE4NFdQkSFL9tdCLTRlrwZWnEyajByVLQznsR3JzZly01DoizTfrSXsXYATli99U2+9UOb+vUR3y6rk6KYWe3RsIr+i46yeEk7b0Yozrpssb4iUgk8drThHFSvmHr3emo=
